# Generated by Django 5.1 on 2024-08-11 05:12

import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfileData',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('degree', models.TextField()),
                ('number', models.CharField(max_length=20)),
                ('years_of_experience', models.TextField()),
                ('skills', models.TextField()),
                ('educational_institutions', models.TextField()),
                ('designation', models.TextField()),
                ('resume_link', models.TextField()),
                ('resume_summary', models.TextField()),
                ('resume_embeddings', pgvector.django.VectorField(dimensions=1536)),
            ],
            options={
                'db_table': 'candidates_profile',
            },
        ),
    ]
